/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post124, git sha1 b5170e139) */

module active_inference_core(tick, bsel, gamma, csel, clk, rst, action, ready, belief_dbg, obs);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire \$10 ;
  wire [8:0] \$11 ;
  wire \$12 ;
  wire [8:0] \$13 ;
  wire [8:0] \$14 ;
  wire \$15 ;
  wire [8:0] \$16 ;
  wire \$17 ;
  wire [8:0] \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire [8:0] \$21 ;
  wire \$22 ;
  wire [8:0] \$23 ;
  wire \$24 ;
  wire [8:0] \$25 ;
  wire [8:0] \$26 ;
  wire \$27 ;
  wire [8:0] \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire [8:0] \$30 ;
  wire [8:0] \$31 ;
  wire \$32 ;
  wire [8:0] \$33 ;
  wire \$34 ;
  wire [8:0] \$35 ;
  wire [8:0] \$36 ;
  wire \$37 ;
  wire [8:0] \$38 ;
  wire \$39 ;
  wire [8:0] \$4 ;
  wire [8:0] \$40 ;
  wire [8:0] \$41 ;
  wire \$42 ;
  wire [8:0] \$43 ;
  wire \$44 ;
  wire [8:0] \$45 ;
  wire [8:0] \$46 ;
  wire \$47 ;
  wire [8:0] \$48 ;
  wire \$49 ;
  wire \$5 ;
  wire [8:0] \$50 ;
  wire [8:0] \$51 ;
  wire [8:0] \$52 ;
  wire \$53 ;
  wire [8:0] \$54 ;
  wire \$55 ;
  wire [8:0] \$56 ;
  wire [8:0] \$57 ;
  wire \$58 ;
  wire [8:0] \$59 ;
  wire [8:0] \$6 ;
  wire \$60 ;
  wire [8:0] \$61 ;
  wire [8:0] \$62 ;
  wire \$63 ;
  wire [8:0] \$64 ;
  wire \$65 ;
  wire [8:0] \$66 ;
  wire [8:0] \$67 ;
  wire [8:0] \$68 ;
  wire \$69 ;
  wire \$7 ;
  wire [8:0] \$70 ;
  wire \$71 ;
  wire [8:0] \$72 ;
  wire [8:0] \$73 ;
  wire \$74 ;
  wire [8:0] \$75 ;
  wire \$76 ;
  wire [8:0] \$77 ;
  wire [8:0] \$78 ;
  wire \$79 ;
  wire [8:0] \$8 ;
  wire [8:0] \$80 ;
  wire \$81 ;
  wire [8:0] \$82 ;
  wire [8:0] \$83 ;
  wire \$84 ;
  wire \$85 ;
  wire [10:0] \$86 ;
  wire [14:0] \$87 ;
  wire [10:0] \$88 ;
  wire [14:0] \$89 ;
  wire [8:0] \$9 ;
  wire [10:0] \$90 ;
  wire [14:0] \$91 ;
  wire \$92 ;
  wire \$93 ;
  reg [7:0] \$94 ;
  reg [7:0] \$95 ;
  reg [7:0] \$96 ;
  reg [1:0] \$97 ;
  reg \$98 ;
  reg [7:0] C0;
  reg [7:0] C1;
  reg [7:0] C2;
  output [1:0] action;
  reg [1:0] action = 2'h0;
  reg [7:0] belief0 = 8'h00;
  reg [7:0] belief1 = 8'h00;
  reg [7:0] belief2 = 8'h00;
  output [7:0] belief_dbg;
  reg [7:0] belief_dbg;
  reg [13:0] best01;
  reg [13:0] bestf;
  input [1:0] bsel;
  wire [1:0] bsel;
  reg [1:0] ch01;
  reg [1:0] chosen;
  input clk;
  wire clk;
  input csel;
  wire csel;
  wire [11:0] d_0;
  wire [11:0] d_1;
  wire [11:0] d_2;
  reg [7:0] ev0;
  reg [7:0] ev1;
  reg [7:0] ev2;
  input [1:0] gamma;
  wire [1:0] gamma;
  reg [7:0] mx01;
  reg [7:0] mxall;
  reg [7:0] nb0;
  reg [7:0] nb1;
  reg [7:0] nb2;
  input [1:0] obs;
  wire [1:0] obs;
  output ready;
  reg ready = 1'h0;
  input rst;
  wire rst;
  wire [9:0] sc_0;
  wire [9:0] sc_1;
  wire [9:0] sc_2;
  wire [13:0] sh_0;
  wire [13:0] sh_1;
  wire [13:0] sh_2;
  reg [9:0] smin;
  reg [9:0] smin01;
  reg [7:0] t_0_0;
  reg [7:0] t_0_1;
  reg [7:0] t_0_2;
  reg [7:0] t_1_0;
  reg [7:0] t_1_1;
  reg [7:0] t_1_2;
  reg [7:0] t_2_0;
  reg [7:0] t_2_1;
  reg [7:0] t_2_2;
  input tick;
  wire tick;
  reg [7:0] upd0;
  reg [7:0] upd1;
  reg [7:0] upd2;
  assign \$2  = ! csel;
  assign \$3  = ! csel;
  assign \$4  = $signed(belief0) + $signed(ev0);
  assign \$5  = $signed(\$4 ) > $signed(8'h7f);
  assign \$6  = $signed(belief0) + $signed(ev0);
  assign \$7  = $signed(\$6 ) < $signed(8'h80);
  assign \$8  = $signed(belief0) + $signed(ev0);
  assign \$9  = $signed(belief1) + $signed(ev1);
  assign \$10  = $signed(\$9 ) > $signed(8'h7f);
  assign \$11  = $signed(belief1) + $signed(ev1);
  assign \$12  = $signed(\$11 ) < $signed(8'h80);
  assign \$13  = $signed(belief1) + $signed(ev1);
  assign \$14  = $signed(belief2) + $signed(ev2);
  assign \$15  = $signed(\$14 ) > $signed(8'h7f);
  assign \$16  = $signed(belief2) + $signed(ev2);
  assign \$17  = $signed(\$16 ) < $signed(8'h80);
  assign \$18  = $signed(belief2) + $signed(ev2);
  assign \$19  = $signed(upd1) > $signed(upd0);
  assign \$20  = $signed(upd2) > $signed(mx01);
  assign \$21  = $signed(upd0) - $signed(mxall);
  assign \$22  = $signed(\$21 ) > $signed(8'h7f);
  assign \$23  = $signed(upd0) - $signed(mxall);
  assign \$24  = $signed(\$23 ) < $signed(8'h80);
  assign \$25  = $signed(upd0) - $signed(mxall);
  assign \$26  = $signed(upd1) - $signed(mxall);
  assign \$27  = $signed(\$26 ) > $signed(8'h7f);
  assign \$28  = $signed(upd1) - $signed(mxall);
  assign \$29  = $signed(\$28 ) < $signed(8'h80);
  assign \$30  = $signed(upd1) - $signed(mxall);
  assign \$31  = $signed(upd2) - $signed(mxall);
  assign \$32  = $signed(\$31 ) > $signed(8'h7f);
  assign \$33  = $signed(upd2) - $signed(mxall);
  assign \$34  = $signed(\$33 ) < $signed(8'h80);
  assign \$35  = $signed(upd2) - $signed(mxall);
  assign \$36  = $signed(nb0) + $signed(C0);
  assign \$37  = $signed(\$36 ) > $signed(8'h7f);
  assign \$38  = $signed(nb0) + $signed(C0);
  assign \$39  = $signed(\$38 ) < $signed(8'h80);
  assign \$40  = $signed(nb0) + $signed(C0);
  assign \$41  = $signed(nb1) + $signed(C0);
  assign \$42  = $signed(\$41 ) > $signed(8'h7f);
  assign \$43  = $signed(nb1) + $signed(C0);
  assign \$44  = $signed(\$43 ) < $signed(8'h80);
  assign \$45  = $signed(nb1) + $signed(C0);
  assign \$46  = $signed(nb2) + $signed(C1);
  assign \$47  = $signed(\$46 ) > $signed(8'h7f);
  assign \$48  = $signed(nb2) + $signed(C1);
  assign \$49  = $signed(\$48 ) < $signed(8'h80);
  assign \$50  = $signed(nb2) + $signed(C1);
  assign \$51  = $signed(t_0_0) + $signed(t_0_1);
  assign sc_0 = $signed(\$51 ) + $signed(t_0_2);
  assign \$52  = $signed(nb0) + $signed(C0);
  assign \$53  = $signed(\$52 ) > $signed(8'h7f);
  assign \$54  = $signed(nb0) + $signed(C0);
  assign \$55  = $signed(\$54 ) < $signed(8'h80);
  assign \$56  = $signed(nb0) + $signed(C0);
  assign \$57  = $signed(nb1) + $signed(C1);
  assign \$58  = $signed(\$57 ) > $signed(8'h7f);
  assign \$59  = $signed(nb1) + $signed(C1);
  assign \$60  = $signed(\$59 ) < $signed(8'h80);
  assign \$61  = $signed(nb1) + $signed(C1);
  assign \$62  = $signed(nb2) + $signed(C2);
  assign \$63  = $signed(\$62 ) > $signed(8'h7f);
  assign \$64  = $signed(nb2) + $signed(C2);
  assign \$65  = $signed(\$64 ) < $signed(8'h80);
  assign \$66  = $signed(nb2) + $signed(C2);
  assign \$67  = $signed(t_1_0) + $signed(t_1_1);
  assign sc_1 = $signed(\$67 ) + $signed(t_1_2);
  assign \$68  = $signed(nb0) + $signed(C1);
  assign \$69  = $signed(\$68 ) > $signed(8'h7f);
  assign \$70  = $signed(nb0) + $signed(C1);
  assign \$71  = $signed(\$70 ) < $signed(8'h80);
  assign \$72  = $signed(nb0) + $signed(C1);
  assign \$73  = $signed(nb1) + $signed(C2);
  assign \$74  = $signed(\$73 ) > $signed(8'h7f);
  assign \$75  = $signed(nb1) + $signed(C2);
  assign \$76  = $signed(\$75 ) < $signed(8'h80);
  assign \$77  = $signed(nb1) + $signed(C2);
  assign \$78  = $signed(nb2) + $signed(C2);
  assign \$79  = $signed(\$78 ) > $signed(8'h7f);
  assign \$80  = $signed(nb2) + $signed(C2);
  assign \$81  = $signed(\$80 ) < $signed(8'h80);
  assign \$82  = $signed(nb2) + $signed(C2);
  assign \$83  = $signed(t_2_0) + $signed(t_2_1);
  assign sc_2 = $signed(\$83 ) + $signed(t_2_2);
  assign \$84  = $signed(sc_1) < $signed(sc_0);
  assign \$85  = $signed(sc_2) < $signed(smin01);
  assign \$86  = $signed(sc_0) - $signed(smin);
  assign \$87  = $signed(\$86 ) << gamma;
  assign \$88  = $signed(sc_1) - $signed(smin);
  assign \$89  = $signed(\$88 ) << gamma;
  assign \$90  = $signed(sc_2) - $signed(smin);
  assign \$91  = $signed(\$90 ) << gamma;
  assign \$92  = $signed(\$89 [13:0]) > $signed(\$87 [13:0]);
  assign \$93  = $signed(\$91 [13:0]) > $signed(best01);
  always @(posedge clk)
    belief0 <= \$94 ;
  always @(posedge clk)
    belief1 <= \$95 ;
  always @(posedge clk)
    belief2 <= \$96 ;
  always @(posedge clk)
    action <= \$97 ;
  always @(posedge clk)
    ready <= \$98 ;
  assign \$1  = ! csel;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      C0 = 8'hb6;
    end else begin
      C0 = 8'hf5;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$2 ) begin
      C1 = 8'hcc;
    end else begin
      C1 = 8'hcc;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$3 ) begin
      C2 = 8'hf5;
    end else begin
      C2 = 8'hb6;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev0 = 8'hf9;
      2'h1:
          ev0 = 8'hb6;
      2'h2:
          ev0 = 8'hb6;
      default:
          ev0 = 8'hf9;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev1 = 8'hb6;
      2'h1:
          ev1 = 8'hf9;
      2'h2:
          ev1 = 8'hb6;
      default:
          ev1 = 8'hb6;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev2 = 8'hb6;
      2'h1:
          ev2 = 8'hb6;
      2'h2:
          ev2 = 8'hf9;
      default:
          ev2 = 8'hb6;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$5 ) begin
      upd0 = 8'h7f;
    end else if (\$7 ) begin
      upd0 = 8'h80;
    end else begin
      upd0 = \$8 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$10 ) begin
      upd1 = 8'h7f;
    end else if (\$12 ) begin
      upd1 = 8'h80;
    end else begin
      upd1 = \$13 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$15 ) begin
      upd2 = 8'h7f;
    end else if (\$17 ) begin
      upd2 = 8'h80;
    end else begin
      upd2 = \$18 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$19 ) begin
      mx01 = upd1;
    end else begin
      mx01 = upd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$20 ) begin
      mxall = upd2;
    end else begin
      mxall = mx01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$22 ) begin
      nb0 = 8'h7f;
    end else if (\$24 ) begin
      nb0 = 8'h80;
    end else begin
      nb0 = \$25 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$27 ) begin
      nb1 = 8'h7f;
    end else if (\$29 ) begin
      nb1 = 8'h80;
    end else begin
      nb1 = \$30 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$32 ) begin
      nb2 = 8'h7f;
    end else if (\$34 ) begin
      nb2 = 8'h80;
    end else begin
      nb2 = \$35 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$37 ) begin
      t_0_0 = 8'h7f;
    end else if (\$39 ) begin
      t_0_0 = 8'h80;
    end else begin
      t_0_0 = \$40 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$42 ) begin
      t_0_1 = 8'h7f;
    end else if (\$44 ) begin
      t_0_1 = 8'h80;
    end else begin
      t_0_1 = \$45 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$47 ) begin
      t_0_2 = 8'h7f;
    end else if (\$49 ) begin
      t_0_2 = 8'h80;
    end else begin
      t_0_2 = \$50 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$53 ) begin
      t_1_0 = 8'h7f;
    end else if (\$55 ) begin
      t_1_0 = 8'h80;
    end else begin
      t_1_0 = \$56 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$58 ) begin
      t_1_1 = 8'h7f;
    end else if (\$60 ) begin
      t_1_1 = 8'h80;
    end else begin
      t_1_1 = \$61 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$63 ) begin
      t_1_2 = 8'h7f;
    end else if (\$65 ) begin
      t_1_2 = 8'h80;
    end else begin
      t_1_2 = \$66 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$69 ) begin
      t_2_0 = 8'h7f;
    end else if (\$71 ) begin
      t_2_0 = 8'h80;
    end else begin
      t_2_0 = \$72 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$74 ) begin
      t_2_1 = 8'h7f;
    end else if (\$76 ) begin
      t_2_1 = 8'h80;
    end else begin
      t_2_1 = \$77 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$79 ) begin
      t_2_2 = 8'h7f;
    end else if (\$81 ) begin
      t_2_2 = 8'h80;
    end else begin
      t_2_2 = \$82 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$84 ) begin
      smin01 = sc_1;
    end else begin
      smin01 = sc_0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$85 ) begin
      smin = sc_2;
    end else begin
      smin = smin01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$92 ) begin
      ch01 = 2'h1;
    end else begin
      ch01 = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$92 ) begin
      best01 = \$89 [13:0];
    end else begin
      best01 = \$87 [13:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$93 ) begin
      chosen = 2'h2;
    end else begin
      chosen = ch01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$93 ) begin
      bestf = \$91 [13:0];
    end else begin
      bestf = best01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (bsel)
      2'h0:
          belief_dbg = belief0;
      2'h1:
          belief_dbg = belief1;
      2'h2:
          belief_dbg = belief2;
      default:
          belief_dbg = belief0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$94  = belief0;
    if (tick) begin
      \$94  = nb0;
    end
    if (rst) begin
      \$94  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$95  = belief1;
    if (tick) begin
      \$95  = nb1;
    end
    if (rst) begin
      \$95  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$96  = belief2;
    if (tick) begin
      \$96  = nb2;
    end
    if (rst) begin
      \$96  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$97  = action;
    if (tick) begin
      \$97  = chosen;
    end
    if (rst) begin
      \$97  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (tick) begin
      \$98  = 1'h1;
    end else begin
      \$98  = 1'h0;
    end
    if (rst) begin
      \$98  = 1'h0;
    end
  end
  assign d_0 = { \$86 [10], \$86  };
  assign sh_0 = \$87 [13:0];
  assign d_1 = { \$88 [10], \$88  };
  assign sh_1 = \$89 [13:0];
  assign d_2 = { \$90 [10], \$90  };
  assign sh_2 = \$91 [13:0];
endmodule
