/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post124, git sha1 b5170e139) */

module active_inference_core(tick, clk, rst, action, ready, belief0, obs);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [8:0] \$1 ;
  wire [8:0] \$10 ;
  wire [8:0] \$11 ;
  wire \$12 ;
  wire [8:0] \$13 ;
  wire \$14 ;
  wire [8:0] \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire [8:0] \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire [8:0] \$20 ;
  wire \$21 ;
  wire [8:0] \$22 ;
  wire [8:0] \$23 ;
  wire \$24 ;
  wire [8:0] \$25 ;
  wire \$26 ;
  wire [8:0] \$27 ;
  wire [8:0] \$28 ;
  wire \$29 ;
  wire [8:0] \$3 ;
  wire [8:0] \$30 ;
  wire \$31 ;
  wire [8:0] \$32 ;
  wire [8:0] \$33 ;
  wire \$34 ;
  wire [8:0] \$35 ;
  wire \$36 ;
  wire [8:0] \$37 ;
  wire [8:0] \$38 ;
  wire \$39 ;
  wire \$4 ;
  wire [8:0] \$40 ;
  wire \$41 ;
  wire [8:0] \$42 ;
  wire [8:0] \$43 ;
  wire \$44 ;
  wire [8:0] \$45 ;
  wire \$46 ;
  wire [8:0] \$47 ;
  wire [8:0] \$48 ;
  wire [8:0] \$49 ;
  wire [8:0] \$5 ;
  wire \$50 ;
  wire [8:0] \$51 ;
  wire \$52 ;
  wire [8:0] \$53 ;
  wire [8:0] \$54 ;
  wire \$55 ;
  wire [8:0] \$56 ;
  wire \$57 ;
  wire [8:0] \$58 ;
  wire [8:0] \$59 ;
  wire [8:0] \$6 ;
  wire \$60 ;
  wire [8:0] \$61 ;
  wire \$62 ;
  wire [8:0] \$63 ;
  wire [8:0] \$64 ;
  wire [8:0] \$65 ;
  wire \$66 ;
  wire [8:0] \$67 ;
  wire \$68 ;
  wire [8:0] \$69 ;
  wire \$7 ;
  wire [8:0] \$70 ;
  wire \$71 ;
  wire [8:0] \$72 ;
  wire \$73 ;
  wire [8:0] \$74 ;
  wire [8:0] \$75 ;
  wire \$76 ;
  wire [8:0] \$77 ;
  wire \$78 ;
  wire [8:0] \$79 ;
  wire [8:0] \$8 ;
  wire [8:0] \$80 ;
  wire \$81 ;
  wire \$82 ;
  reg [7:0] \$83 ;
  reg [7:0] \$84 ;
  reg [7:0] \$85 ;
  reg [1:0] \$86 ;
  reg \$87 ;
  wire \$9 ;
  wire [9:0] acc_a0;
  wire [9:0] acc_a1;
  wire [9:0] acc_a2;
  output [1:0] action;
  reg [1:0] action = 2'h0;
  output [7:0] belief0;
  reg [7:0] belief0 = 8'h00;
  (* init = 8'h00 *)
  wire [7:0] \belief0$7 ;
  reg [7:0] belief1 = 8'h00;
  reg [7:0] belief2 = 8'h00;
  reg [9:0] best01;
  reg [9:0] best2;
  reg [1:0] ch01;
  reg [1:0] chosen2;
  input clk;
  wire clk;
  reg [7:0] ev0;
  reg [7:0] ev1;
  reg [7:0] ev2;
  reg [7:0] mx01;
  reg [7:0] mx2;
  reg [7:0] nb0;
  reg [7:0] nb1;
  reg [7:0] nb2;
  input [1:0] obs;
  wire [1:0] obs;
  output ready;
  reg ready = 1'h0;
  input rst;
  wire rst;
  reg [7:0] t_a0_s0;
  reg [7:0] t_a0_s1;
  reg [7:0] t_a0_s2;
  reg [7:0] t_a1_s0;
  reg [7:0] t_a1_s1;
  reg [7:0] t_a1_s2;
  reg [7:0] t_a2_s0;
  reg [7:0] t_a2_s1;
  reg [7:0] t_a2_s2;
  input tick;
  wire tick;
  reg [7:0] upd0;
  reg [7:0] upd1;
  reg [7:0] upd2;
  assign \$13  = $signed(belief2) + $signed(ev2);
  assign \$14  = $signed(\$13 ) < $signed(8'h80);
  assign \$15  = $signed(belief2) + $signed(ev2);
  assign \$16  = $signed(upd1) > $signed(upd0);
  assign \$17  = $signed(upd2) > $signed(mx01);
  assign \$18  = $signed(upd0) - $signed(mx2);
  assign \$19  = $signed(\$18 ) > $signed(8'h7f);
  assign \$20  = $signed(upd0) - $signed(mx2);
  assign \$21  = $signed(\$20 ) < $signed(8'h80);
  assign \$22  = $signed(upd0) - $signed(mx2);
  assign \$23  = $signed(upd1) - $signed(mx2);
  assign \$24  = $signed(\$23 ) > $signed(8'h7f);
  assign \$25  = $signed(upd1) - $signed(mx2);
  assign \$26  = $signed(\$25 ) < $signed(8'h80);
  assign \$27  = $signed(upd1) - $signed(mx2);
  assign \$28  = $signed(upd2) - $signed(mx2);
  assign \$29  = $signed(\$28 ) > $signed(8'h7f);
  assign \$30  = $signed(upd2) - $signed(mx2);
  assign \$31  = $signed(\$30 ) < $signed(8'h80);
  assign \$32  = $signed(upd2) - $signed(mx2);
  assign \$33  = $signed(nb0) + $signed(8'hb6);
  assign \$34  = $signed(\$33 ) > $signed(8'h7f);
  assign \$35  = $signed(nb0) + $signed(8'hb6);
  assign \$36  = $signed(\$35 ) < $signed(8'h80);
  assign \$37  = $signed(nb0) + $signed(8'hb6);
  assign \$38  = $signed(nb1) + $signed(8'hb6);
  assign \$39  = $signed(\$38 ) > $signed(8'h7f);
  assign \$40  = $signed(nb1) + $signed(8'hb6);
  assign \$41  = $signed(\$40 ) < $signed(8'h80);
  assign \$42  = $signed(nb1) + $signed(8'hb6);
  assign \$43  = $signed(nb2) + $signed(7'h4c);
  assign \$44  = $signed(\$43 ) > $signed(8'h7f);
  assign \$45  = $signed(nb2) + $signed(7'h4c);
  assign \$46  = $signed(\$45 ) < $signed(8'h80);
  assign \$47  = $signed(nb2) + $signed(7'h4c);
  assign \$48  = $signed(t_a0_s0) + $signed(t_a0_s1);
  assign acc_a0 = $signed(\$48 ) + $signed(t_a0_s2);
  assign \$49  = $signed(nb0) + $signed(8'hb6);
  assign \$50  = $signed(\$49 ) > $signed(8'h7f);
  assign \$51  = $signed(nb0) + $signed(8'hb6);
  assign \$52  = $signed(\$51 ) < $signed(8'h80);
  assign \$53  = $signed(nb0) + $signed(8'hb6);
  assign \$54  = $signed(nb1) + $signed(7'h4c);
  assign \$55  = $signed(\$54 ) > $signed(8'h7f);
  assign \$56  = $signed(nb1) + $signed(7'h4c);
  assign \$57  = $signed(\$56 ) < $signed(8'h80);
  assign \$58  = $signed(nb1) + $signed(7'h4c);
  assign \$59  = $signed(nb2) + $signed(5'h15);
  assign \$60  = $signed(\$59 ) > $signed(8'h7f);
  assign \$61  = $signed(nb2) + $signed(5'h15);
  assign \$62  = $signed(\$61 ) < $signed(8'h80);
  assign \$63  = $signed(nb2) + $signed(5'h15);
  assign \$64  = $signed(t_a1_s0) + $signed(t_a1_s1);
  assign acc_a1 = $signed(\$64 ) + $signed(t_a1_s2);
  assign \$65  = $signed(nb0) + $signed(7'h4c);
  assign \$66  = $signed(\$65 ) > $signed(8'h7f);
  assign \$67  = $signed(nb0) + $signed(7'h4c);
  assign \$68  = $signed(\$67 ) < $signed(8'h80);
  assign \$69  = $signed(nb0) + $signed(7'h4c);
  assign \$70  = $signed(nb1) + $signed(5'h15);
  assign \$71  = $signed(\$70 ) > $signed(8'h7f);
  assign \$72  = $signed(nb1) + $signed(5'h15);
  assign \$73  = $signed(\$72 ) < $signed(8'h80);
  assign \$74  = $signed(nb1) + $signed(5'h15);
  assign \$75  = $signed(nb2) + $signed(5'h15);
  assign \$76  = $signed(\$75 ) > $signed(8'h7f);
  assign \$77  = $signed(nb2) + $signed(5'h15);
  assign \$78  = $signed(\$77 ) < $signed(8'h80);
  assign \$79  = $signed(nb2) + $signed(5'h15);
  assign \$80  = $signed(t_a2_s0) + $signed(t_a2_s1);
  assign acc_a2 = $signed(\$80 ) + $signed(t_a2_s2);
  assign \$81  = $signed(acc_a1) > $signed(acc_a0);
  assign \$82  = $signed(acc_a2) > $signed(best01);
  always @(posedge clk)
    belief0 <= \$83 ;
  always @(posedge clk)
    belief1 <= \$84 ;
  always @(posedge clk)
    belief2 <= \$85 ;
  always @(posedge clk)
    action <= \$86 ;
  always @(posedge clk)
    ready <= \$87 ;
  assign \$1  = $signed(belief0) + $signed(ev0);
  assign \$2  = $signed(\$1 ) > $signed(8'h7f);
  assign \$3  = $signed(belief0) + $signed(ev0);
  assign \$4  = $signed(\$3 ) < $signed(8'h80);
  assign \$5  = $signed(belief0) + $signed(ev0);
  assign \$6  = $signed(belief1) + $signed(ev1);
  assign \$7  = $signed(\$6 ) > $signed(8'h7f);
  assign \$8  = $signed(belief1) + $signed(ev1);
  assign \$9  = $signed(\$8 ) < $signed(8'h80);
  assign \$10  = $signed(belief1) + $signed(ev1);
  assign \$11  = $signed(belief2) + $signed(ev2);
  assign \$12  = $signed(\$11 ) > $signed(8'h7f);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev0 = 8'hf9;
      2'h1:
          ev0 = 8'hb6;
      2'h2:
          ev0 = 8'hb6;
      default:
          ev0 = 8'hf9;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev1 = 8'hb6;
      2'h1:
          ev1 = 8'hf9;
      2'h2:
          ev1 = 8'hb6;
      default:
          ev1 = 8'hb6;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (obs)
      2'h0:
          ev2 = 8'hb6;
      2'h1:
          ev2 = 8'hb6;
      2'h2:
          ev2 = 8'hf9;
      default:
          ev2 = 8'hb6;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$2 ) begin
      upd0 = 8'h7f;
    end else if (\$4 ) begin
      upd0 = 8'h80;
    end else begin
      upd0 = \$5 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$7 ) begin
      upd1 = 8'h7f;
    end else if (\$9 ) begin
      upd1 = 8'h80;
    end else begin
      upd1 = \$10 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$12 ) begin
      upd2 = 8'h7f;
    end else if (\$14 ) begin
      upd2 = 8'h80;
    end else begin
      upd2 = \$15 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$16 ) begin
      mx01 = upd1;
    end else begin
      mx01 = upd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$17 ) begin
      mx2 = upd2;
    end else begin
      mx2 = mx01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$19 ) begin
      nb0 = 8'h7f;
    end else if (\$21 ) begin
      nb0 = 8'h80;
    end else begin
      nb0 = \$22 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$24 ) begin
      nb1 = 8'h7f;
    end else if (\$26 ) begin
      nb1 = 8'h80;
    end else begin
      nb1 = \$27 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$29 ) begin
      nb2 = 8'h7f;
    end else if (\$31 ) begin
      nb2 = 8'h80;
    end else begin
      nb2 = \$32 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$34 ) begin
      t_a0_s0 = 8'h7f;
    end else if (\$36 ) begin
      t_a0_s0 = 8'h80;
    end else begin
      t_a0_s0 = \$37 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$39 ) begin
      t_a0_s1 = 8'h7f;
    end else if (\$41 ) begin
      t_a0_s1 = 8'h80;
    end else begin
      t_a0_s1 = \$42 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$44 ) begin
      t_a0_s2 = 8'h7f;
    end else if (\$46 ) begin
      t_a0_s2 = 8'h80;
    end else begin
      t_a0_s2 = \$47 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$50 ) begin
      t_a1_s0 = 8'h7f;
    end else if (\$52 ) begin
      t_a1_s0 = 8'h80;
    end else begin
      t_a1_s0 = \$53 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$55 ) begin
      t_a1_s1 = 8'h7f;
    end else if (\$57 ) begin
      t_a1_s1 = 8'h80;
    end else begin
      t_a1_s1 = \$58 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$60 ) begin
      t_a1_s2 = 8'h7f;
    end else if (\$62 ) begin
      t_a1_s2 = 8'h80;
    end else begin
      t_a1_s2 = \$63 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$66 ) begin
      t_a2_s0 = 8'h7f;
    end else if (\$68 ) begin
      t_a2_s0 = 8'h80;
    end else begin
      t_a2_s0 = \$69 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$71 ) begin
      t_a2_s1 = 8'h7f;
    end else if (\$73 ) begin
      t_a2_s1 = 8'h80;
    end else begin
      t_a2_s1 = \$74 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$76 ) begin
      t_a2_s2 = 8'h7f;
    end else if (\$78 ) begin
      t_a2_s2 = 8'h80;
    end else begin
      t_a2_s2 = \$79 [7:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$81 ) begin
      ch01 = 2'h1;
    end else begin
      ch01 = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$81 ) begin
      best01 = acc_a1;
    end else begin
      best01 = acc_a0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$82 ) begin
      chosen2 = 2'h2;
    end else begin
      chosen2 = ch01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$82 ) begin
      best2 = acc_a2;
    end else begin
      best2 = best01;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$83  = belief0;
    if (tick) begin
      \$83  = nb0;
    end
    if (rst) begin
      \$83  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$84  = belief1;
    if (tick) begin
      \$84  = nb1;
    end
    if (rst) begin
      \$84  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$85  = belief2;
    if (tick) begin
      \$85  = nb2;
    end
    if (rst) begin
      \$85  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$86  = action;
    if (tick) begin
      \$86  = chosen2;
    end
    if (rst) begin
      \$86  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (tick) begin
      \$87  = 1'h1;
    end else begin
      \$87  = 1'h0;
    end
    if (rst) begin
      \$87  = 1'h0;
    end
  end
  assign \belief0$7  = belief0;
endmodule
